Impliment functions to play sound. Add sound/
su-its/ams-backend-nodejs pull request #16
Opened 2021-03-04 03:51 UTC by h-takeyeah

#15 について簡単に書いてみました．`sound/`ディレクトリにまだ音声ファイルが足らないですが，取り急ぎレビューお願いします．

2021-03-04 04:23 UTC, equal-l2 requested changes

2021-03-04 04:23 UTC, equal-l2 commented on app/controllers/readerInputController.ts
> +  res.status(200).send('OK')
追加情報がないのであればstatus 200だけで十分かと思います

2021-03-04 04:23 UTC, equal-l2 commented on app/controllers/readerInputController.ts
> +    playWav(Status.FATAL)
invalidなstatusが来た場合はそもそも不正な相手が送ってきているので音は流さなくていいと思います。
(デバッグ用にログくらいは吐いておいていいとは思いますが)

それもそうだし、Status.FATALは「rdr-bridgeはもう終わりよ〜ん」というメッセージなのでここで使うのは不適切かも

2021-03-04 04:23 UTC, equal-l2 commented on app/controllers/readerInputController.ts
> +    for (const itr of Object.values(Status)) {
ここはどういう動作を意図したコードですか？（JS弱）

2021-03-04 04:23 UTC, equal-l2 commented on app/controllers/readerInputController.ts
> +      /* isValidStatus()でちぇっくするので多分ここには来ない */
ここに来る場合はなんかおかしいのでログ吐いといた方がいいです

2021-03-04 04:23 UTC, equal-l2 commented on app/controllers/readerInputController.ts
> +function playWav (...fileName: string[]) {
2個以上の音声を連続で流すことは現状ありますか？
もしなければ引数は1個にしてください。

2021-03-04 04:23 UTC, equal-l2 commented on app/controllers/readerInputController.ts
> +function playWav (...fileName: string[]) {
YAGNIを原則としてもろて

2021-03-04 04:23 UTC, equal-l2 commented on app/controllers/readerInputController.ts
> +    playWav(Status.FATAL)
ここで音を出すと某室に恨みのある人間が無限に変なリクエストを投げて騒音問題を引き起こすことができてしまいます

2021-03-04 04:23 UTC, equal-l2 commented on app/controllers/readerInputController.ts
> +    spawnSync('aplay', ['-q', f + '.wav'], { cwd: WAV_FILE_DIR, stdio: 'inherit' })
引数が1個ならasyncなやつを使っても大丈夫かと思います

2021-03-04 04:23 UTC, equal-l2 commented on app/controllers/readerInputController.ts
>  const handleReaderInput = async (req: Request, res: Response) => {
ついでにここを `async function handlerReaderInput ...` の形式に書き直してもらえますか？
(何か不便があるならその旨教えてください)

2021-03-04 04:42 UTC, equal-l2 commented on app/controllers/readerInputController.ts
> +    playWav(Status.FATAL)
そうすると、不正なリクエストの時は400返しといた方が親切かな

2021-03-04 05:59 UTC, equal-l2 commented on app/controllers/readerInputController.ts
> +    spawnSync('aplay', ['-q', f + '.wav'], { cwd: WAV_FILE_DIR, stdio: 'inherit' })
asyncだとプロセスが死ぬまで世話してあげないといけなくて面倒っぽいので、やっぱりこのままでいいです。

2021-03-04 06:53 UTC, h-takeyeah reviewed
各々の指摘には返信しましたがこの枠には何を書けばいいんでしょう？

2021-03-04 06:53 UTC, h-takeyeah commented on app/controllers/readerInputController.ts
> +    playWav(Status.FATAL)
> invalidなstatusが来た場合はそもそも不正な相手が送ってきているので音は流さなくていいと思います。
> (デバッグ用にログくらいは吐いておいていいとは思いますが)
> 
> それもそうだし、Status.FATALは「rdr-bridgeはもう終わりよ〜ん」というメッセージなのでここで使うのは不適切かも

Status.FATALをbackend側のエラーのように使ってしまっていて不適切でしたね．不正なリクエストはログに出して(すなわち音以外の方法で)おくようにします．

2021-03-04 06:53 UTC, h-takeyeah commented on app/controllers/readerInputController.ts
> +    playWav(Status.FATAL)
いきなり200を返しているところも変なので何かしら判断してから，400も含め，何を返すか決めるようなコードにします．

2021-03-04 06:55 UTC, h-takeyeah reviewed
@Stroheim001 さんへ @equal-l2 さんにレビューしてもらいつつ，確認しながら書きましたが明らかに変なところがあったら指摘お願いします．

2021-03-04 07:03 UTC, h-takeyeah commented on app/controllers/readerInputController.ts
> +  res.status(200).send('OK')
200で中身がないことが気持ち悪いと思うのでいっそ204にしますかねえ．

2021-03-04 07:03 UTC, h-takeyeah commented on app/controllers/readerInputController.ts
> +    playWav('error')
reader-bridgeのエラーではないので音を鳴らさないか鳴らすにしても別の音の方がいいかもしれないです

2021-03-04 08:22 UTC, equal-l2 requested changes

2021-03-04 08:22 UTC, equal-l2 commented on app/controllers/readerInputController.ts
> +  spawnSync('aplay', ['-q', fileName + '.wav'], { cwd: WAV_FILE_DIR, stdio: 'inherit' })
あとでspawnSyncを使った理由を忘れるといけないので、「asyncなspawnだとChildProcessが返ってきて世話するのが面倒くさいので、spawnSyncを使う」とか書いておいてください。

2021-03-04 08:57 UTC, h-takeyeah commented on app/controllers/readerInputController.ts
> +  spawnSync('aplay', ['-q', fileName + '.wav'], { cwd: WAV_FILE_DIR, stdio: 'inherit' })
了解しました．そんな感じに書きます．

2021-03-06 06:32 UTC, equal-l2 approved these changes

2021-03-06 17:12 UTC, Stroheim001 commented
@h-takeyeah レビューが遅くなって申し訳ありません。

動くかどうかは明日dockerで試してみますが、responseに400、500(これが出ることは絶対にないけど)が一応設定されているため、OpenAPIとの乖離が起きています。

これは仕様書と違う状態が生まれてしまうので早めに潰しておきたいです。音が出たらレビューOK出そうと思います。以上です。

2021-03-07 03:25 UTC, Stroheim001 commented on tsconfig.json
>      // "incremental": true,                   /* Enable incremental compilation */
これ、しれっと重要な変更されてる気がするけど周知しなくて大丈夫？

2021-03-07 03:25 UTC, Stroheim001 commented on app/controllers/readerInputController.ts
> +  // stdio: 'inherit'でnodeのstdioを子プロセスにも使わせる
この辺のコメントは、関数の外のほうが分かりやすいかもね

2021-03-07 04:01 UTC, h-takeyeah commented on tsconfig.json
>      // "incremental": true,                   /* Enable incremental compilation */
@Stroheim001 すみません．完全に言い忘れてました．targetをes5からes2017にしたのはarrayのincludes()がそれ以降じゃないと使えなかったからです．

この需要を満たすために，targetを引き上げる方法(いまの状態)と，targetは変えずにlibに["es5", "es2017"]を指定する方法の2つがあると思いますが，node14は[ここ](https://node.green/#ES2017)を見る限りでは引き上げてしまっても大丈夫そうなので前者の方法をとっています．

2021-03-07 04:08 UTC, h-takeyeah commented on app/controllers/readerInputController.ts
> +  // stdio: 'inherit'でnodeのstdioを子プロセスにも使わせる
@Stroheim001 関数の中に書くには少し長いかなと自分も思いました．

```javascript
/**
 * stdio: 'inherit'でnodeのstdioを子プロセスにも使わせる
 * asyncなspawnだとChildProcessが返ってきて世話するのが面倒くさいので、spawnSyncを使う
 * 順番通りに最後まで再生したいのでspawnSyncを使う
 */
function playWav (fileName: string) {
```

直すとすればこうでしょうか？

2021-03-07 04:11 UTC, h-takeyeah commented on app/controllers/readerInputController.ts
> +  // stdio: 'inherit'でnodeのstdioを子プロセスにも使わせる
jsdoc的にはこう？

```javascript
/**
 * wavファイルを再生する
 * @param {string} fileName - 再生するファイルの名前を指定する
 * @return {void}
 *  
 * stdio: 'inherit'でnodeのstdioを子プロセスにも使わせる
 * asyncなspawnだとChildProcessが返ってきて世話するのが面倒くさいので、spawnSyncを使う
 * 順番通りに最後まで再生したいのでspawnSyncを使う
 * /
function playWav (fileName: string) {
```

2021-03-07 04:20 UTC, Stroheim001 commented on tsconfig.json
>      // "incremental": true,                   /* Enable incremental compilation */
了解しました。割と重要な話だと思うので開発者全員に周知とマージをお願いするようにした方が良いと思います。

2021-03-07 04:21 UTC, Stroheim001 commented on app/controllers/readerInputController.ts
> +  // stdio: 'inherit'でnodeのstdioを子プロセスにも使わせる
jsdoc風が良いかと思います。
もしdoc化する時に有用だと思いますし、ドキュメントを気にしてくれるようになってくれて嬉しいなと思っています

2021-03-07 04:25 UTC, h-takeyeah commented on app/controllers/readerInputController.ts
> +  // stdio: 'inherit'でnodeのstdioを子プロセスにも使わせる
了解しました．すぐ取り掛かりたいのですが，このブランチをベースに文法的なlintを少し生やしてしまっているのでそれらを取り込んでからやるべきだと考えています．ですのでdoc化はissueとして立てておきますね．

2021-03-07 04:25 UTC, merged