まだ足りてない修正漏れを治した
su-its/ams-backend-nodejs pull request #18
Opened 2021-03-04 14:04 UTC by Stroheim001

記載していたイラストを差し替え

APIの仕様を記述した。

APIをhtmlに出力し、誰でも見えるようにした。またhtmlに出力できるようにするやり方を記述した。

2021-03-04 14:14 UTC, equal-l2 approved these changes

2021-03-05 00:57 UTC, h-takeyeah approved these changes

2021-03-05 01:21 UTC, h-takeyeah commented
@Stroheim001 本当にすみません。承認押してから気づいたのですが`ams-backend-nodes.yml`内に間違いらしき箇所があったので伝えます。

https://github.com/su-its/ams-backend-nodejs/blob/79451ac8ab1427e170e6f245564d5756a35fb6bf/docs/OpenAPI/ams-backend-nodejs.yml#L39-L63

- 50行目はuser_idではなくてstatusの間違いだと思います。
- 45行目の説明は入退室時の情報更新を行うのはバックエンドの仕事でありカードリーダーもといブリッジから送られてくるPOSTのボディーには含まれていません。この説明も間違いではないのですが基本的にはブリッジ自身の状態を表すのがstatusです。ですから、そのように書き直してもらえると適切かと思います。カードと正しく通信できたかどうか？そもそもカードの情報を読み取るどころではない(そもそもリーダーが接続されていないなど)などの異常はないか？などがこのstatusで判断できます。

https://github.com/su-its/ams-backend-nodejs/blob/79451ac8ab1427e170e6f245564d5756a35fb6bf/docs/OpenAPI/ams-backend-nodejs.yml#L95-103

- いない場合はErrではなくnullを返します。

2021-03-05 01:24 UTC, h-takeyeah requested changes
(↑の変更の要請を忘れないための空のレビュー)

2021-03-05 08:50 UTC, h-takeyeah approved these changes
ありがとうございます．全部見ました．オーケーです！

2021-03-05 08:51 UTC, h-takeyeah approved these changes
package-lock.jsonの修正確認しました

2021-03-05 08:52 UTC, merged