ページネーション
su-its/ams-backend-nodejs pull request #35
Opened 2021-03-07 12:06 UTC by equal-l2

closes #23

---

クエリパラメータ`page`を受け取ってページネーションできるようにしました。

返ってくるJSONは以下のような形式です:

```json5
{
  "page": 2,
  "next_page": "http://localhost:3000/v1/access_logs?page=3",
  "prev_page": "http://localhost:3000/v1/access_logs?page=1",
  "total_page": 15,
  "data": [
    {
      "user_id": 1,
      "entered_at": "2021-02-23T16:57:39.000Z",
      "exited_at": "2021-02-23T17:32:50.000Z"
    }
	// データ……
  ]
}
```

2021-03-07 12:28 UTC, Stroheim001 commented
@equal-l2 テスティングしておきます。自分の作業が終わったらすぐやりたいと思います。

2021-03-07 13:06 UTC, h-takeyeah commented
@equal-l2 自分もテストしてみます

2021-03-07 16:15 UTC, h-takeyeah requested changes
@equal-l2 PRありがとうございます．テストしました．ページネーションがバリバリ動いていてすごいです！あとは日付で絞る機能も付けられたら付けたいですね～(今は一時的にそのあたりの引数にundefinedを渡しているようでしたので)．

2021-03-07 16:15 UTC, h-takeyeah commented on app/controllers/accessLogsController.ts
> +    const urlOfEndpoint = req.protocol + '://' + req.hostname + ':' + amsOptions.port + req.path
43行目，`urlOfEndpoint`の最後は`req.path`ではなく`req.baseUrl + req.path`が良いと思います．`req.path`だけだと`hostname`と`path`の間の部分(今回は`v1`にあたる部分)が消えてしまうので．

[Express 4.x - API リファレンス](https://expressjs.com/ja/4x/api.html#req.baseUrl)

2021-03-07 16:15 UTC, h-takeyeah commented on app/models/accessLogsModel.ts
> +export { createAccessLog, listAccessLogs, getCountOfAccessLogs }
気にするほどのことでもないのですが，自分ルールとして関数をアルファベット順に並べて定義するぞというのを持っていたので，それに倣ってもらってexportもアルファベット順にc，g，lと並べていただけるととても嬉しいです．ただ，`getCountOfAccessLogs`はメインどころの関数ではないので下の方にあるのでもいいと思います．

2021-03-07 16:22 UTC, equal-l2 commented on docs/OpenAPI/ams-backend-nodejs.yml
> +            type:
ここは型として `"#/components/schemas/Log"` を参照しています。
ただ `$ref`を使う場合 `type` を指定しているのはおかしいので直します。

2021-03-07 16:27 UTC, h-takeyeah commented on docs/OpenAPI/ams-backend-nodejs.yml
> +            type:
なるほど，そういうルールなのですね．

2021-03-07 16:42 UTC, equal-l2 commented on app/models/accessLogsModel.ts
> +export { createAccessLog, listAccessLogs, getCountOfAccessLogs }
修正しました。

---

ちなみに、eslintに `sort-imports` というのがあるのでそれを有効にするとよいと思います。
https://eslint.org/docs/rules/sort-imports

2021-03-07 16:42 UTC, equal-l2 commented on app/controllers/accessLogsController.ts
> +    const urlOfEndpoint = req.protocol + '://' + req.hostname + ':' + amsOptions.port + req.path
修正しました。

2021-03-07 16:48 UTC, h-takeyeah approved these changes
@equal-l2 確認しました

2021-03-07 16:49 UTC, h-takeyeah commented on docs/OpenAPI/ams-backend-nodejs.yml
> +            type:
修正確認しました

2021-03-08 04:29 UTC, Stroheim001 approved these changes
@equal-l2 遅くなって申し訳ありません。
今動作確認しました。大丈夫です。

2021-03-08 04:30 UTC, Stroheim001 commented
@h-takeyeah mergeの方よろしくお願いします。

2021-03-08 05:21 UTC, h-takeyeah commented
遅くなってすみません．マージしておきます

2021-03-08 05:21 UTC, merged