Iss17
su-its/ams-backend-nodejs pull request #43
Opened 2021-03-10 15:32 UTC by h-takeyeah

Server-Sent eventsで入室および退室イベントが発生した時にフロントエンドに在室者の配列を投げます。

```json5
// 例
[
  {
    "user_id": 1234,
    "user_name": "辻野あかり"
    "entered_at": "2021-03-10T14:54:59.000Z"
  },
  // 以下同...
]
```

クライアントサイドではこんな感じでデータが取得できます．JavaScriptの例です．

```javascript
const evtSource = new EventSource('http://localhost:3000/v1/sse')

evtSource.addEventListener('error', err => {
  console.error(err)
  // 再読み込みした時にも出るかも
  alert('サーバーとの通信が切断されました(再読み込みした時にも表示されます)')
})

// event名が指定されていないイベントが来たらこれが呼ばれる
evtSource.addEventListener('message', msgEvent => {
  console.log(msgEvent.data)
})

// イベント名は任意
evtSource.addEventListener('usersUpdated', msgEvent => {
  try {
    // dataプロパティが万一なかったらとりあえずからの配列を出す
    console.log(JSON.parse(msgEvent?.data ?? []))
  } catch (err) {
    console.error(err)
  }
})

// コネクションを確立したら呼ばれる
evtSource.addEventListener('open', event => {
  console.log('conneection established! (Event Source Interface)')
})
```

まだ実現できていないのは
- `user_name`プロパティ(メンバーを登録する・読み出すAPIが生えてないのでまだ無理．作るまで全員りんごアイドルになってもらう)
- 在室人数を示すプロパティが無い(付けろと言われればすぐ付けられる)
です．他にも思い出したら付け足します．レビューお願いします．
---
close #17

2021-03-10 15:36 UTC, equal-l2 commented
PR名を、PRの内容がわかるように変更してください。

2021-03-10 15:48 UTC, equal-l2 requested changes

2021-03-10 15:48 UTC, equal-l2 commented on app/controllers/sseController.ts
> +    'Cache-Control': 'no-cache' // 参考にしたサイトの多くでしようされていたのでno-cacheを指定(無くてもよさげ)
typoです。
```suggestion
    'Cache-Control': 'no-cache' // 参考にしたサイトの多くで使用されていたのでno-cacheを指定(無くてもよさげ)
```

2021-03-10 15:48 UTC, equal-l2 commented on app/controllers/sseController.ts
> +  if (emitter.listenerCount('usersUpdated') + 1 > EventEmitter.defaultMaxListeners) {
ここのifって、(ないとは思いますが)単純に10人以上がイベントをlistenしようとした場合にも条件満たしますか？

2021-03-10 15:48 UTC, equal-l2 commented on app/routes/sseRoutes.ts
> +router.get('/sse', sseHandler)
エンドポイントの名前をもう少し記述的に(`userUpdateEvent`とか?)にした方がいいと思います。
今の実装だと、将来的に複数イベントを扱う場合、各イベントごとに別個のエンドポイントを用意することになるはずなので。

2021-03-10 15:58 UTC, h-takeyeah commented on app/controllers/sseController.ts
> +  if (emitter.listenerCount('usersUpdated') + 1 > EventEmitter.defaultMaxListeners) {
「単純に」というのは，今はこれしかありませんがHTTPリクエスト経由で以外の場合も含めて，リスナーが登録される場合を考えてのことだと思いますが，条件を満たします．

2021-03-10 16:01 UTC, h-takeyeah commented on app/controllers/sseController.ts
> +        user.user_name = '辻野あかり'
分かりました．:apple:は学籍番号の文字列表現に変えておきます．

2021-03-10 16:03 UTC, h-takeyeah commented on app/controllers/sseController.ts
> +  if (emitter.listenerCount('usersUpdated') + 1 > EventEmitter.defaultMaxListeners) {
ありません．

2021-03-10 16:04 UTC, h-takeyeah commented on app/controllers/sseController.ts
> +        user.user_name = '辻野あかり'
@equal-l2 と思ったのですが，nullやundefinedの方が良いですか？

2021-03-10 16:04 UTC, equal-l2 commented on app/controllers/sseController.ts
> +        user.user_name = '辻野あかり'
意図としては「バックエンドが送る名前が、フロントエンドでひとまず表示されるか確認したい」ということですね？
もしそうでないなら、バックエンドがnullなりを送ってきた場合フロントエンドで適当にフォールバックすることもできるので。

2021-03-10 16:07 UTC, h-takeyeah commented on app/controllers/sseController.ts
> +        user.user_name = '辻野あかり'
ではフロントエンド側に任せてnullを設定します

2021-03-10 16:18 UTC, h-takeyeah commented on app/routes/sseRoutes.ts
> +router.get('/sse', sseHandler)
`users_update_event`に変更しました．複数形なのはuser1人の更新ではなくusers、一覧の更新だからです．

2021-03-10 16:32 UTC, equal-l2 commented on app/controllers/sseController.ts
> +  if (emitter.listenerCount('usersUpdated') + 1 > EventEmitter.defaultMaxListeners) {
まあ現状だとイベントを受ける人が1つだけなのでいいですが、理想的にはその辺もちゃんとハンドルしたいですね

2021-03-10 16:34 UTC, equal-l2 commented on app/controllers/sseController.ts
> +  if (emitter.listenerCount('usersUpdated') + 1 > EventEmitter.defaultMaxListeners) {
SSEってHTTPコネクションを張りっぱなしにして、その経路を使ってサーバからPushするわけですよね。
イベントから外されてもそのコネクションは張りっぱなしなんでしょうか？
(コネクションが切れればフロントエンドはそこからアクションを起こせる)

2021-03-11 01:17 UTC, h-takeyeah commented on app/controllers/sseController.ts
> +  if (emitter.listenerCount('usersUpdated') + 1 > EventEmitter.defaultMaxListeners) {
分かりにくい書き方でしたがこの警告はnodeの内部で使うイベントのことです．ですから警告に対してやっている処理は単にその内部的なイベントエミッターからリスナーを外すというだけのものです．クライアントとのコネクションを切るにはストリームの終了を示す何か(あるかどうか調べます)を送るか異常系のステータスコードを返すかが必要になるのかと思います．

パッとリンクが出ないですが，Qiitaで見かけた実装ではHTTPリクエストが来るごとにクライアントを配列に追加しクローズしたくなった段階で配列から取り除くというような処理をしていました．

2021-03-11 03:04 UTC, equal-l2 commented on app/controllers/sseController.ts
> +  if (emitter.listenerCount('usersUpdated') + 1 > EventEmitter.defaultMaxListeners) {
話を聞く限りだと現行の実装では、リスナーを外されたフロントエンドたちはコネクションはつながったまま永久に来ることのないイベントを待ち続けることになると思うんですが正しいですか？

2021-03-11 04:52 UTC, h-takeyeah commented on app/controllers/sseController.ts
> +  if (emitter.listenerCount('usersUpdated') + 1 > EventEmitter.defaultMaxListeners) {
そうだと思います

2021-03-11 04:54 UTC, h-takeyeah commented
@equal-l2 @Stroheim001 言い忘れてましたがバックエンドから投げられてくるのはJSON.stringify()した文字列です．

2021-03-11 04:57 UTC, equal-l2 commented on app/controllers/sseController.ts
> +  if (emitter.listenerCount('usersUpdated') + 1 > EventEmitter.defaultMaxListeners) {
わかりました。
ひとまず動くとは思うのでこのPRではそこのエラーハンドルは要求しませんが、将来的にはほしいので `//FIXME` なり `//TODO` なりでこの一連の会話で判明した問題を記載しておいてください。

2021-03-11 05:09 UTC, Stroheim001 commented
了解です

2021-03-12 09:21 UTC, equal-l2 requested changes

2021-03-12 09:21 UTC, equal-l2 commented on app/controllers/sseController.ts
> +    'Cache-Control': 'no-cache', // 参考にしたサイトの多くで使用されていたのでno-cacheを指定(無くてもよさげ)
今回の場合だとそもそもキャッシュされても困るので `no-store` の方がいいかもしれません
(SSEでもサイトによって `no-store` を使っています。この辺のベストプラクティスが知りたい……)
https://stackoverflow.com/a/31130747

2021-03-12 09:21 UTC, equal-l2 commented on app/controllers/sseController.ts
> +    Connection: 'keep-alive' // 参考にしたサイトの多くで使用されていたので
`keep-alive` は「次回以降のHTTPリクエストでも同じコネクションを使ってね」というものなので、ここだけでやっても意味なさそう

---

ちなみにHTTP2だとHTTPレベルでキープアライブすること自体禁止されてます
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Connection

2021-03-12 10:46 UTC, h-takeyeah commented on app/controllers/sseController.ts
> +    'Cache-Control': 'no-cache', // 参考にしたサイトの多くで使用されていたのでno-cacheを指定(無くてもよさげ)
了解しました．`no-store`に変更します．余談ですが，リクエストとレスポンスで`Cache-Control`が一致していなければいけないというわけではないのですね．

> Cache-Control は HTTP のヘッダーで、リクエストとレスポンスの両方でキャッシュのためのディレクティブ (指示) が格納されています。リクエストで指定されたディレクティブは、レスポンスでも同じディレクティブを使用しなければならないということではありません。https://developer.mozilla.org/ja/docs/Web/HTTP/Headers/Cache-Control

2021-03-12 10:53 UTC, h-takeyeah commented on app/controllers/sseController.ts
> +    'Cache-Control': 'no-cache', // 参考にしたサイトの多くで使用されていたのでno-cacheを指定(無くてもよさげ)
`no-store`に変更しました．レスポンスがブラウザにキャッシュされることはなくなったと思います．

2021-03-12 10:54 UTC, h-takeyeah commented on app/controllers/sseController.ts
> +    Connection: 'keep-alive' // 参考にしたサイトの多くで使用されていたので
`keep-alive`消しました．

2021-03-12 11:03 UTC, equal-l2 approved these changes

2021-03-12 11:14 UTC, h-takeyeah commented
@equal-l2 @Stroheim001 SSEのエンドポイントは`/v1/users_updated_event`になります．複数形，過去形で分かりにくいと思うのでメモしておきます．

2021-03-12 11:14 UTC, merged