フロントエンドへの通知(再)細かい改良を加えた
su-its/ams-backend-nodejs pull request #54
Opened 2021-03-12 21:44 UTC by h-takeyeah

- 他のエンドポイントにならって返すJSONにdataプロパティを作り，そこに配列データを引っつけるように変更した．(実際返すときは文字列になってる)
- 接続が切れたときの対策を見直した
- SSEに関係はないが，ルーターにバリデーションを追加した．
- その他，誤字脱字の修正などを行った．

2021-03-12 22:45 UTC, equal-l2 commented on app/routes/sseRoutes.ts
> +// router.get('/subscribe', addSubscriber) // こっちでもいいかも
MDNを見た感じ、EventSourceオブジェクトはパス以外でイベントを選べないようです。
したがって、もし単一エンドポイントにして複数イベントをハンドルする場合、`/subscribe?event=userUpdated`のようにクエリを受け取れるようにしてやる必要があります。

2021-03-12 23:24 UTC, Stroheim001 commented on app/routes/sseRoutes.ts
> +// router.get('/subscribe', addSubscriber) // こっちでもいいかも
@h-takeyeah 頓珍漢な事言ってたら申し訳ないのですが、データのupdateならそもそもgetではなくputが適切な気がします。

2021-03-12 23:37 UTC, equal-l2 commented on app/routes/sseRoutes.ts
> +// router.get('/subscribe', addSubscriber) // こっちでもいいかも
このエンドポイントはSSEがイベント通知にsubscribeするためのものです。
技術的にそのsubscribeはPOSTでもできないことはないですが、これをブラウザでやるための`EventSource`というクラスが基本的にGETしか投げられないので、ここはGETにした方が楽です。

2021-03-12 23:51 UTC, Stroheim001 commented on app/routes/sseRoutes.ts
> +// router.get('/subscribe', addSubscriber) // こっちでもいいかも
@equal-l2 すみません、頓珍漢なこと言ってしまいました。get,put,post,deleteを使ってCRUD操作できるものと勘違いしてました。了解です。

2021-03-13 00:56 UTC, equal-l2 commented on app/routes/sseRoutes.ts
> +// router.get('/subscribe', addSubscriber) // こっちでもいいかも
@h-takeyeah このトピックの最初の件ですが、クライアント側が欲しいイベントのみを送らないといけない場合にのみ真でした。
SSEを勉強していてわかりましたが、サーバが送ってくるイベントにクライアントが `addEventListener` でリスナーをくっつけて使うものなんですね。これなら一つのエンドポイントで複数イベントを扱えます。

まあ、エンドポイントを分ければイベント名を付けなくてもクライアント側で `message` イベントを見るだけでいいので楽は楽かもですが……

2021-03-13 01:06 UTC, Stroheim001 commented on app/controllers/sseController.ts
> +      user.user_name = null
@h-takeyeah 
これは今はまだ名前は出力されないよ？って意味であってますか？

将来実装予定があると思うのですがTODOなりつけておいた方が良いかと...

頓珍漢だったらごめんなさい

2021-03-13 01:35 UTC, equal-l2 requested changes

2021-03-13 01:35 UTC, equal-l2 commented on app/controllers/sseController.ts
> +      client.res.status(204).end()
ここでステータスコードを送っていますが、規格上ステータスコードは最初の接続に成功した時点で送らないといけません。
>HTTP 200 OK responses [...] must be processed [...].
>Any other HTTP response code [...] must cause the user agent to fail the connection.
https://html.spec.whatwg.org/multipage/server-sent-events.html#sse-processing-model

最初にステータスコードを送るということは、そこ以外でステータスを設定しても意味がないということです。

最初にステータスコードを送る方法については`addSubscriber`付近に詳しい修正方法を書きます。

2021-03-13 01:35 UTC, equal-l2 commented on app/controllers/sseController.ts
>    })
ここの直下で [`res.flushHeaders`](https://nodejs.org/api/http.html#http_request_flushheaders) を呼んでヘッダ（ステータス含む）を送ってあげてください。
なお、ステータスはデフォルトで200に設定されているので別途設定する必要はありません。

以後ステータスを設定しても意味がないので、該当する部分は消しておいてください。

2021-03-13 01:35 UTC, equal-l2 commented on app/controllers/sseController.ts
> +    id: id, // 登録した時刻でクライアントを識別する
(厳密には同じ時間に接続したクライアントを混同する可能性があるけど、まあ今回のユースケースなら気にしなくていいか……)

2021-03-13 01:42 UTC, h-takeyeah commented on app/controllers/sseController.ts
> +      user.user_name = null
@Stroheim001 それで合ってます．将来，番号と名前を紐づけたテーブルを作って，登録されている人は番号だけでなく名前も表示されるようにできたらいいなと考えています．今はまだできていないので，おっしゃる通りまだ名前はないよという意味でnullを入れています．

そういう意味ですのでnullに当たったときにはフロントエンドの側でフォールバックして0埋めするとか名前の欄にも番号を出すなど対応してもらえると助かります．

2021-03-13 01:50 UTC, Stroheim001 commented on app/controllers/sseController.ts
> +      user.user_name = null
@h-takeyeah ええと、該当するページは最初のページであってますか？？？

2021-03-13 02:04 UTC, h-takeyeah commented on app/controllers/sseController.ts
>    })
`status()`を削除し`flushHeaders()`を使うように変更しました．

2021-03-13 02:50 UTC, equal-l2 approved these changes

2021-03-13 02:54 UTC, Stroheim001 commented on app/controllers/sseController.ts
> +      user.user_name = null
@equal-l2 このメソッドはどのページに該当しますか？

最初のページという認識なのですが、そうではなく、バージョン情報以外全部の共通の処理とかですか

2021-03-13 02:58 UTC, equal-l2 commented on app/controllers/sseController.ts
> +      user.user_name = null
在室者一覧を表示するためのデータを送る部分なので `index.vue` とか `InRoomUsers.vue` ですね

---

今思ったけど、`/users_in_room`から来るJSONにも`user_name`フィールドがないとまずい状況では？
(`users_in_room`とSSEは同じものを送るようになってて欲しい)

2021-03-13 03:00 UTC, Stroheim001 commented on app/controllers/sseController.ts
> +      user.user_name = null
@equal-l2 
とりあえず最初のページだけということは分かりました。

出すのは簡単ですがAPI作ったり、リバースエンジニアリングするためのドキュメント作るのは死ぬほど大変なので、

まあ、コメント入れたり図使ったりしてアーキテクチャ分かりやすくしておいてください。

最悪私がなんか図とかは作ります。

2021-03-13 03:18 UTC, equal-l2 commented
@Stroheim001 マージしちゃって大丈夫でしょうか？
SSEをNuxtにねじ込む実装を今やっているので、APIが変わるこのPRがdevelopに入らないと身動き取れないので……

2021-03-13 03:50 UTC, Stroheim001 commented
@equal-l2 食事をとってました。すみません。

やむを得ない対応なら仕方ないと思いますが、websocketにしておけば...ってことになってなければいいですけど

APIとフロントの密度が一時的に高まるのが暫定的措置ならいいと思いますが、極力分けるつもりでいてください。

必要ならmilestoneを使って将来的に結合度を下げてテスティングしやすくする事も視野に入れてほしいです。

2021-03-13 11:50 UTC, equal-l2 commented on app/controllers/sseController.ts
> +      user.user_name = null
@h-takeyeah 
以下の件どうですか？
> /users_in_roomから来るJSONにもuser_nameフィールドがないとまずい

2021-03-13 11:58 UTC, Stroheim001 commented
@h-takeyeah @equal-l2 
これ、だいぶ前にも言いましたけど、とりあえず仕上がったらこれでごりおすしかないんですよね？

2021-03-13 12:09 UTC, h-takeyeah commented
ゴリ押すというのは？

2021-03-13 15:10 UTC, h-takeyeah commented on app/controllers/sseController.ts
> +      user.user_name = null
@equal-l2
返信遅れてすみません．

`/users_in_room`に`user_name`を付与する変更には賛成です．自分はこの質問をされたとき，`/users_in_room`は内部的には`in_room_users`というテーブルに対応しているエンドポイントであり，そのフィールドに`user_name`は存在しないから吐くJSONに`user_name`が含まれているのはおかしいと考えていました．しかし`/access_logs`の例を考えてみると，テーブルのスキーマとエンドポイントから吐かれるデータのスキーマが完全に対応していることが必ずしも正義ではないように思えてきました．

`/access_logs`にその不一致を許す以上，そして@equal-l2さんのおっしゃる通り`/users_in_room`とSSEが等しく現在の部屋の状況を吐くエンドポイントである以上，`/users_in_room`と内部のテーブルの対応より`/users_in_room`とSSEの吐くデータ構造が一致することの方が重要であると考え，`/users_in_room`に`user_name`を付与する変更を加えるべきだという結論に至りました．あとは無くて損することはありますけど，あって損することはないよね，って理由もあります．

自分はそういう意見です．

---

以下，考えたこと

(*) 入退室記録を画面上に出す，およびCSVに書き出すときはあれば`user_name`も一緒に引っ張ってきたいですよね．そうなると現在の実装で絶対に`user_name`の需要があるのはここではなく`/access_logs`なのでは？と思いました．

別の方法として`user_id`と`user_name`の紐づけを保存しておくテーブル`members`に対応するエンドポイント`/members/{user_id}`を新たに作成するというのもあります．エンドポイントとテーブルの対応およびエンドポイント間でのテーブルの棲み分けができていて素晴らしい作戦です．ですがクライアントは次の手順を踏むことになり，さすがにクライアント側がめんどくさそうです．

入退室記録を表示したい(あるいはそれをCSVにかきだしたい)ときクライアントのたどる手順↓
1. `/access_logs`に任意の期間の入退室記録一覧を問い合わせる
2. 一覧に登場する`user_id`で`/members`に問合せ，`user_name`を取得する
3. `user_id`をキーにして`user_id`，`user_name`，`entered_at`，`exited_at`のカラムを持つ行を作成
4. 2と3を`user_id`の分だけ繰り返して表を完成させる

ですから入退室記録一覧に名前(`user_name`)も含みたいと相なったらそれはAPI側で引っ付けて送る用にした方がいいでしょう．

2021-03-13 16:11 UTC, Stroheim001 commented
@h-takeyeah @equal-l2 
結合が起きてしまい、API的な振る舞いをフロントエンドにも行うことを意味するんですよね？

で、それしか方法がないのなら、やむを得ないのですが、将来的にリファクタリングを予定していて欲しいです。

2021-03-14 09:53 UTC, Stroheim001 approved these changes
指摘取り込みお疲れ様でした。

頑張ってください

2021-03-14 09:53 UTC, merged