OpenAPIの修正とPM2の説明
su-its/ams-backend-nodejs pull request #59
Opened 2021-03-13 09:37 UTC by h-takeyeah

- PM2の説明を`deployment.md`に記載した
- OpenAPIの修正をした

本当はPM2だけのつもりだったのですが，気づいたらOpenAPIの修正も混ざってしまいました．本当にごめんなさい．PM2にかんする追記は次の通りです．
- ecosystem.config.jsの説明
- ログの形式，見方などの説明
- PM2のアップデート時のトラブルシューティング的な何か

とりあえずdeployment.mdに書きましたが，もし他のファイルに書いた方が良いということであればそうしますのでごきょうじゅください．

2021-03-13 10:02 UTC, Stroheim001 commented on docs/deployment.md
> +```bash
@h-takeyeah 私の個人的な趣味ではあるのですが、[bash]で囲っておいた方がbashであると明示できると思って毎回そうやってます。(何かで囲ってないと不安)

余裕があったら出良いので、redpenだけでも良いのでかけてみてください。表記ゆれとかそういうのあると思います。

運が良ければ、textlintもmergeされられたらな、と思ってます。

2021-03-13 11:43 UTC, equal-l2 requested changes

2021-03-13 11:43 UTC, equal-l2 commented on docs/OpenAPI/ams-backend-nodejs.yml
> +      summary: 在室中のとある1人のユーザ情報を取得
-「とある1人のユーザ」だと"a random user"感ある
- 別に在室中でなくてもこのエンドポイントは使える(その確認に使うので)

以上の理由から、「特定ユーザ1名のユーザ情報を取得」とかにするとよさそう。

2021-03-13 11:43 UTC, equal-l2 commented on docs/OpenAPI/ams-backend-nodejs.yml
> +      description: 在室中のユーザのArrayをJSONで返す
戻ってくるのは「ユーザのユーザ情報のArray」ですね

2021-03-13 11:43 UTC, equal-l2 commented on docs/OpenAPI/ams-backend-nodejs.yml
> +      description: 特定のユーザが在室しているか確認するために使える
他のパスのdescriptionは、summaryで記述された返ってくる値をより具体的に説明したものになっています。
ここもそのように揃えて欲しいです。

2021-03-13 11:43 UTC, equal-l2 commented on docs/deployment.md
> +    script: 'npm',       // これと
単なる質問なんですが、例えばscriptに `sh` と書いてargsに `start` と書けばpm2でシェルスクリプトを実行することもできるわけですか？
もしそうなら今SystemdのUnitで動かしてる連中(rdr-bridgeだけですが)も移行できそうかなと……

2021-03-13 11:43 UTC, equal-l2 commented on docs/deployment.md
> +PM2はグローバルインストールされているのでnpmあるいはnodeのバージョンを上げるとPM2は削除されると思います
> 削除されると思います

もし正しいと思っているのなら自信を持って言い切ってください。
自信の持てない記述は削除してください。

2021-03-13 11:43 UTC, equal-l2 commented on docs/deployment.md
> +この場合でも`~/.pm2/dump.pm2`は残るので古いバージョンのPM2の設定で起動しようとして失敗する可能性が高いです
> 失敗する可能性が高いです

根拠を明示するか、(正しいのなら)「可能性」で濁さずに言い切ってください。

2021-03-13 11:43 UTC, equal-l2 commented on docs/deployment.md
> +pm2 start 何か # 本リポジトリのコードはpm2 start ecosystem.config.jsで起動できる
何かを挿入すべき部分は`[ほげ]`とか`<ふが>`のように何かしらの括弧で括ってくれた方が親切です。

2021-03-13 11:43 UTC, equal-l2 commented on docs/deployment.md
> +OSの起動時に本リポジトリ、ams-backend-nodejsのプログラムを自動起動させ、落ちたら再起動させるなどの処理を担うPM2について簡単に説明します
主語がめちゃくちゃ後ろに来ているので、「PM2について説明します。PM2はOSの起動時に……などの処理を担っています」のように文を切ってください。

(この節自体がPM2の説明なので、説明しますという必要すらないかもですが)

2021-03-13 11:52 UTC, Stroheim001 commented on docs/OpenAPI/ams-backend-nodejs.yml
> +      summary: 在室中のとある1人のユーザ情報を取得
特定の、と、とある、では aとtheくらい意味が違う気がします...

2021-03-13 11:53 UTC, equal-l2 commented on docs/OpenAPI/ams-backend-nodejs.yml
> +      summary: 在室中のとある1人のユーザ情報を取得
そもそも技術文書に「とある」というのが出てくるのが違和感あります。
APIを使う人はどのユーザの情報を知りたいのかわかっているわけですから、ここでは「特定の」の方がいいと思いました。

2021-03-13 11:54 UTC, Stroheim001 commented on docs/deployment.md
> +PM2はグローバルインストールされているのでnpmあるいはnodeのバージョンを上げるとPM2は削除されると思います
仮にそこまで自信がなかったとしても、次のLTSにあげた際に互換性があるかのチェックが必要になります。くらいはあっても良いのではないでしょうか。

2021-03-13 11:56 UTC, Stroheim001 commented on docs/deployment.md
> +この場合でも`~/.pm2/dump.pm2`は残るので古いバージョンのPM2の設定で起動しようとして失敗する可能性が高いです
apiの話なので、分からないですが、nuxtは全部作り直すことになるので、古いデータが残ることはなかったです。

が、万が一起きたときは該当ディレクトリを一度消して、リビルドするという手順を記載すると良いかもしれません。

2021-03-13 11:56 UTC, equal-l2 commented on docs/deployment.md
> +PM2はグローバルインストールされているのでnpmあるいはnodeのバージョンを上げるとPM2は削除されると思います
バージョンアップ時のチェックは必要だとは思います。
ただこの節が最終的に言いたいことが「問題が起きたときにpm2を再セットアップする方法」になっているので、そこに向かう理由がふわふわしすぎているかなと思ったところです。

2021-03-13 12:00 UTC, Stroheim001 commented on docs/OpenAPI/ams-backend-nodejs.yml
> +      summary: 在室中のとある1人のユーザ情報を取得
まあそういう、技術文書にふさわしくない文書を弾くためのツールがtextlintとそのプラグインなのですが...

何か目印になるものがあると良いですね...

2021-03-13 12:01 UTC, Stroheim001 commented on docs/deployment.md
> +PM2はグローバルインストールされているのでnpmあるいはnodeのバージョンを上げるとPM2は削除されると思います
なるほど、了解です。

書き方としては、ファジーですね

2021-03-13 12:11 UTC, h-takeyeah commented on docs/deployment.md
> +    script: 'npm',       // これと
と思います

2021-03-13 12:12 UTC, h-takeyeah commented on docs/deployment.md
> +OSの起動時に本リポジトリ、ams-backend-nodejsのプログラムを自動起動させ、落ちたら再起動させるなどの処理を担うPM2について簡単に説明します
分かりました

2021-03-13 13:56 UTC, h-takeyeah commented on docs/deployment.md
> +```bash
@Stroheim001 `[]`で囲っておいた方が明示できる感じは分かるのですが，GitHubのmarkdownの中のコードブロックは`[bash]`ではなく`bash`と書かないとシンタックスハイライトが機能しないのでこうしました．

2021-03-13 15:16 UTC, h-takeyeah commented on docs/OpenAPI/ams-backend-nodejs.yml
> +      summary: 在室中のとある1人のユーザ情報を取得
書いた当時，わざわざ「在室中の」との枕詞を付けたのはユーザーという用語とメンバー(学籍番号と名前がDBに記録されている人)とという用語が混同されることを避けるためでした．

今メンバーは無いけれども，用語が浸透していないかもしれないという懸念があるのはその辺の共有ができていないことの裏返しだったなと反省しております．

2021-03-13 16:12 UTC, Stroheim001 commented on docs/deployment.md
> +```bash
@h-takeyeah 失礼しました

了解です。

2021-03-14 06:35 UTC, h-takeyeah commented on docs/OpenAPI/ams-backend-nodejs.yml
> +              example:
`application/json`(Media Type Object)のメンバとして`schema`やら`example`やらを書くように変更しました．こうしないと`example`に書いてあることがHTMLに反映されませんでした．

https://swagger.io/specification/

2021-03-14 06:36 UTC, h-takeyeah commented on docs/OpenAPI/ams-backend-nodejs.yml
> +      summary: ユーザ情報一覧を取得
「在室中の」を削除して，「ユーザを取得」ではなく「ユーザ情報を取得」に変更しました．

2021-03-14 06:37 UTC, h-takeyeah commented on docs/OpenAPI/ams-backend-nodejs.yml
> +              example:
access_logsのところと同じ意図

2021-03-14 06:38 UTC, h-takeyeah commented on docs/OpenAPI/ams-backend-nodejs.yml
> +      description: 指定されたユーザのユーザ情報もしくは NO CONTENT を返す
`description`を`summary`を詳しく説明するような内容に変更した．

2021-03-14 06:39 UTC, h-takeyeah commented on docs/OpenAPI/ams-backend-nodejs.yml
> +              example:
access_logsのところと同じ意図

2021-03-14 06:40 UTC, h-takeyeah reviewed
指摘を取り込んだ部分を説明するコメントを追加しました

2021-03-14 11:58 UTC, equal-l2 commented on docs/deployment.md
> +pm2 updatePM2 # pm2 updateでも可
併記している理由は何ですか？

2021-03-14 12:11 UTC, equal-l2 commented on docs/deployment.md
> +pm2 updatePM2 # pm2 updateでも可
どちらかがcanonicalなやり方なのであればそちらだけを書いておいてください。

2021-03-14 13:56 UTC, equal-l2 approved these changes

2021-03-14 13:59 UTC, merged