[WIP]Docs_CI_Test
su-its/ams-backend-nodejs pull request #60
Opened 2021-03-13 12:04 UTC by Stroheim001

github actions が仕様変更が多すぎて、リバースエンジニアリングして変数名を考えているところです。

2021-03-13 12:10 UTC, equal-l2 requested changes
多分今回導入した連中は自分が導入したaction-eslintと同じシリーズだと思うので、そっちのymlが参考になるかもしれません。
https://github.com/su-its/ams-backend-nodejs/blob/develop/.github/workflows/reviewdog.yml

2021-03-13 12:10 UTC, equal-l2 commented on .github/workflows/ci.yml
> +          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
デフォルトで指定してくれてるのでなくてよさそう

2021-03-13 12:10 UTC, equal-l2 commented on .github/workflows/ci.yml
> +          INPUT_REVIEWDOG_FLAGS: true
これはどういうやつでしょう?
(reviewdog_flags は reviewdogコマンドに渡す追加の引数だと思っていますが)

2021-03-13 12:14 UTC, equal-l2 commented
今`INPUT_***`で書いてる部分、説明書に書いてあるとおり小文字で書いても勝手に変換されるので、そちらで書いてもよさそうです。
https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepswith

2021-03-13 15:57 UTC, Stroheim001 commented
@equal-l2 github acrions の設定のパラメータがverごとに違うみたいで、github_tokenはGITHUB_TOKENに

最近変更らしいのですが、どれが大文字・小文字関係ないのかはわかってないので、もらったURLちゃんと読んでおきます

2021-03-13 15:59 UTC, Stroheim001 commented on .github/workflows/ci.yml
> +          INPUT_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
readmeでrequaredになってるものがあります

2021-03-13 16:00 UTC, Stroheim001 commented on .github/workflows/ci.yml
> +          INPUT_REVIEWDOG_FLAGS: true
あ！！そういうことか！！

修正しておきます！！

2021-03-14 20:13 UTC, equal-l2 commented
`github_token`ですが、やはり省略できそうです。
自分の使った `action-eslint` でも `github_token` は `required` と書いてありましたが、デフォルト値が定まっているので省略できました。

念のためこのPRで使われている全てのactionの `action.yml` を見てきましたが、どれでも `github_token` にはデフォルト値が設定されているので、省略できるものと思われます。
(デフォルト値があるのに `required` というのがそもそも変な話ですが……)

2021-03-14 21:55 UTC, Stroheim001 commented
@equal-l2 了解です。actionsはreviewdogの仕様が難しいっぽいですね

2021-03-15 05:29 UTC, closed without merging

2021-03-15 05:36 UTC, Stroheim001 commented
これはヤバいので辞めておきます。