句点、句読点を通常の会話で使用するものに変更した
su-its/ams-backend-nodejs pull request #69
Opened 2021-03-16 17:46 UTC by Stroheim001

普段の会話で使用できる「、」「。」を許可する
close #68

2021-03-16 17:49 UTC, equal-l2 commented
行き違いになってしまってすみません。
このPRで現存文書内の句読点を「、。」に置き換えていただけますか？

（ちなみになんですが、句読点は句点「。」と読点「、」の総称なので、「句点、句読点」と並列するのは変です）

2021-03-16 18:17 UTC, Stroheim001 commented
@equal-l2 よかった。もう句読点の変換やってます。

句読点の使い方間違えてました。申し訳ないです。

2021-03-16 19:08 UTC, Stroheim001 commented
@equal-l2 遅くなりました。修正完了しました

2021-03-16 19:58 UTC, equal-l2 commented on docs/deployment.md
> +pm2 は OS の起動時に本リポジトリ、 ams-backend-nodejs のプログラムを自動起動させ、落ちたら再起動させるなどの処理を担当しています。
公式ホームページによれば大文字表記の PM2 が正しいプロダクト名です。
特別な理由がなければ小文字の pm2 にした部分を元に戻してください。

2021-03-16 20:00 UTC, equal-l2 commented on docs/OpenAPI/how_to_generate.md
> +### インストールコマンド
この小見出しは不要だと思うので文言ごと削除してしまいましょう

2021-03-16 21:16 UTC, Stroheim001 commented on docs/OpenAPI/how_to_generate.md
> +### インストールコマンド
意味が重複してるので消しておきます

2021-03-16 21:16 UTC, Stroheim001 commented on docs/deployment.md
> +pm2 は OS の起動時に本リポジトリ、 ams-backend-nodejs のプログラムを自動起動させ、落ちたら再起動させるなどの処理を担当しています。
すみません。正式な名前に準拠するべきですね。

元に戻しておきます。

2021-03-17 00:31 UTC, equal-l2 requested changes

2021-03-17 00:31 UTC, equal-l2 commented on docs/deployment.md
> +## pm2のインストール（まだの場合）
大文字PM2に戻してください

2021-03-17 00:31 UTC, equal-l2 commented on docs/deployment.md
> +デバッグをするときは直接 npm スクリプトを実行するか、pm2 が ams-backend を走らせている状態でログを監視するのがよいでしょう。
大文字PM2に戻してください

2021-03-17 00:36 UTC, Stroheim001 commented on docs/deployment.md
> +## pm2のインストール（まだの場合）
直します

2021-03-17 00:36 UTC, Stroheim001 commented on docs/deployment.md
> +デバッグをするときは直接 npm スクリプトを実行するか、pm2 が ams-backend を走らせている状態でログを監視するのがよいでしょう。
抜け漏れがありました、治します。

2021-03-17 00:40 UTC, Stroheim001 commented
@equal-l2 自分も文書の達人ではないので、ドキュメントがかくあるべきかは、悩みの種なのですが、今はこれの対応を行いますが、いずれdeployment.mdも文言自体が修正する、と考えて大丈夫ですね？
(それ用のissueは出しておきましたけども...)

2021-03-17 00:48 UTC, equal-l2 approved these changes

2021-03-17 00:49 UTC, equal-l2 commented
長きにわたる修正にお付き合いいただきありがとうございます。
マージします。

2021-03-17 00:53 UTC, merged